# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkedin-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "97a3ee2b86089d12d04fbf437cda016e53f2c342975bc2aaecaa3592b5243370"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7168c0d375d868ac7f4e51386227cfd3324e53f23fbd5d9661163f1f56cc4a9f"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "542b4655749814f684d09ea007b46dcd624463a1c7f9376c1792e8bb823f53d7"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa3158741cc2d0d1fcff9498a82ca8474d2293c7be0732e05cbd059caaf49194"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "linkedin-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/linkedin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkedin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkedin"]
  end

  # No zap stanza required

end
