# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkedin-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "377f423d5f800183893a5df53c42c8715d46349aad72f9217924e21e5d9667f0"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a810e44e2868585a08f76d1ab8d818b4c6b412b4894ef11cbb47ef2eeb91b072"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0d3d398bf8e0378e56ac2e629060ae4b7f0fd7ca934f69cfd04e7aff1c72664"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1fbf6ee4c7152c18fef64055f3344c1140588663dc2d17bccc639514bd7bff0"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "linkedin-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/linkedin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkedin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkedin"]
  end

  # No zap stanza required

end
