# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkedin-cli" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "41e041e0fa1323a67247222f5f04dbf53ff60a88bae7c35c7d0c4a47f628a088"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "05ea686f4eae3478aeb7bd2a321e3fe20ae451dffbfc83bfe20a7ec2d268e1ad"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b2a63f58e2e39ea3889a2a5867d0565f32a9555a3831dc6e85931103bc758c0"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "caa0f275cfc8893f596e5f6e0c60022da620b4e59556aa169e665e9bd31c6006"
      url "https://github.com/jjuanrivvera/linkedin-cli/releases/download/v#{version}/linkedin-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "linkedin-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/linkedin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkedin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkedin"]
  end

  # No zap stanza required
end
